server:
  http2:
    enabled: ${HTTP2_ENABLE:false}
  port: ${PORT:8443}
  ssl:
    enabled: ${SSL_ENABLE:false}
    keystore: ${KEYSTORE_PATH:}
    keystore-password: ${KEYSTORE_PASSWORD:}
    key-store-type: ${KEYSTORE_TYPE:}
